name: Run Gradle on Pushes

on: push
jobs:
  gradle:
    name: Build the mod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Actually build it
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build